version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fidc
      POSTGRES_PASSWORD: fidc
      POSTGRES_DB: fidc
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fidc"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build: .
    command: ["sh","-c","/wait-db.sh db python run.py"]
    env_file: .env.example
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_started
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  worker:
    build: .
    command: ["sh","-c","/wait-db.sh db celery -A celery_worker.celery worker --loglevel=info"]
    env_file: .env.example
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      api:
        condition: service_started
    volumes:
      - ./:/app

volumes:
  minio_data: