version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: fidc
      POSTGRES_PASSWORD: fidc
      POSTGRES_DB: fidc
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fidc"]
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9001:9001"

  api:
    build: .
    command: ["/wait-for-db.sh", "python", "run.py"]
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
    ports:
      - "5000:5000"
    volumes:
      - ./:/app

  worker:
    build: .
    command: ["/wait-for-db.sh", "celery", "-A", "celery_worker.celery", "worker", "--loglevel=info"]
    env_file: .env
    depends_on:
      - db
      - redis
      - api
    volumes:
      - ./:/app

volumes:
  minio_data:
